In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

In [3]:
df = pd.read_csv('groundwater_ml_dataset.csv')
df.head(10)

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
0,1,Safe,4951.0,73.39,16.51,66.57,Safe,0.003335,0.224963,0.6657,0.224459,2024
1,2,Semi Critical,711.0,10.54,2.82,11.40,Safe,0.003966,0.267552,0.1140,0.131407,2024
2,3,Critical,206.0,3.05,0.88,3.55,Safe,0.004272,0.288525,0.0355,0.124219,2024
3,4,Over-Exploited,751.0,11.13,4.20,16.93,Safe,0.005593,0.377358,0.1693,0.187040,2024
4,5,Saline,127.0,1.88,0.38,1.55,Safe,0.002992,0.202128,0.0155,0.085148,2024
5,S. No.,Ground Water Resources Assessment,2004.0,2009.00,2011.00,2013.00,Over Exploited,1.003493,1.000996,20.1300,4.827795,2024
6,2,Safe,4078.0,71.30,4277.00,73.20,Semi Critical,1.048798,59.985975,0.7320,24.560309,2024
7,3,Semi-critical,550.0,9.60,523.00,9.00,Safe,0.950909,54.479167,0.0900,22.190030,2024
8,4,Critical,226.0,3.90,169.00,2.90,Safe,0.747788,43.333333,0.0290,17.638248,2024
9,5,Over-Exploited,839.0,14.70,802.00,13.70,Safe,0.955900,54.557823,0.1370,22.232889,2024

In [4]:
df.isnull().sum()

state                   0
district                0
annual_recharge         0
extractable_resource    0
annual_extraction       0
stage_of_development    0
category                0
extraction_ratio        0
utilization_rate        0
stress_level            0
risk_score              0
year                    0
dtype: int64

In [5]:
df.columns

Index(['state', 'district', 'annual_recharge', 'extractable_resource',
       'annual_extraction', 'stage_of_development', 'category',
       'extraction_ratio', 'utilization_rate', 'stress_level', 'risk_score',
       'year'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1932 entries, 0 to 1931
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 1932 non-null   object
 1   district              1932 non-null   object
 2   annual_recharge       1932 non-null   float64
 3   extractable_resource  1932 non-null   float64
 4   annual_extraction     1932 non-null   float64
 5   stage_of_development  1932 non-null   float64
 6   category              1932 non-null   object
 7   extraction_ratio      1932 non-null   float64
 8   utilization_rate      1932 non-null   float64
 9   stress_level          1932 non-null   float64
 10  risk_score            1932 non-null   float64
 11  year                  1932 non-null   int64
dtypes: float64(8), int64(1), object(3)
memory usage: 181.3+ KB

In [7]:
df.tail()

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
1927,24,Telangana,620.0,9.0,76.0,527.0,Over Exploited,0.122581,8.444444,5.27,4.480810,2024
1928,26,Uttar Pradesh,836.0,22.0,12.0,802.0,Over Exploited,0.014354,0.545455,8.02,1.827923,2024
1929,28,West Bengal,345.0,4.0,4.0,337.0,Over Exploited,0.011594,1.000000,3.37,1.078638,2024
1930,30,Chandigarh,1.0,1.0,0.0,0.0,Safe,0.000000,0.000000,0.00,0.000000,2024
1931,36,Ladakh,18.0,5.0,0.0,13.0,Safe,0.000000,0.000000,0.13,0.026000,2024

In [8]:
df.describe()

,annual_recharge,extractable_resource,annual_extraction,stage_of_development,extraction_ratio,utilization_rate,stress_level,risk_score,year
count,1.932000e+03,1932.000000,1.932000e+03,1.932000e+03,1932.000000,1932.000000,1932.000000,1932.000000,1932.0
mean,2.498134e+04,9044.642834,3.981354e+03,1.375984e+04,2.019403,197.685596,137.598428,107.401685,2024.0
std,4.242728e+04,14319.993642,4.925726e+04,1.663539e+05,34.489025,5859.608905,1663.538529,2366.504676,0.0
min,1.000000e-02,0.001000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,2024.0
25%,1.087050e+03,416.217500,5.334500e+01,1.975325e+02,0.016619,0.039353,1.975325,1.550143,2024.0
50%,1.634041e+04,2566.885000,3.027250e+02,2.686880e+03,0.082253,0.164024,26.868800,9.312073,2024.0
75%,3.656483e+04,12023.240000,2.606145e+03,1.343459e+04,0.239509,1.208592,134.345875,27.828603,2024.0
max,1.412285e+06,102516.480000,2.147413e+06,7.283766e+06,1330.000000,232791.000000,72837.661500,93116.696531,2024.0

In [9]:
df.iloc[10:31]

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
10,6,Saline,30.00,0.50,71.00,1.20,Safe,2.366667,142.000000,0.0120,57.749067,2024
11,2,ASSAM,0.50,26.00,88.70,108.50,Over Exploited,177.400000,3.411538,1.0850,72.541615,2024
12,3,MEGHALAYA,0.10,7.40,133.00,81.10,Semi Critical,1330.000000,17.972973,0.8110,539.351389,2024
13,4,NAGALAND,0.30,2.10,45.00,62.20,Safe,150.000000,21.428571,0.6220,68.695829,2024
14,8,SIKKIM,0.70,99.00,196.00,200.90,Over Exploited,280.000000,1.979798,2.0090,113.193719,2024
15,9,WEST BENGAL,0.10,1.70,62.70,41.10,Safe,627.000000,36.882353,0.4110,265.635141,2024
16,13,UTTARAKHAND,30.60,6.60,63.50,64.00,Safe,2.075163,9.621212,0.6400,4.806550,2024
17,17,PUNJAB,15.10,0.10,56.60,26.00,Safe,3.748344,566.000000,0.2600,227.951338,2024
18,18,HIMACHALPRADESH,86.80,30.00,66.70,103.50,Over Exploited,0.768433,2.223333,1.0350,1.403707,2024
19,20,LADAKH(UT),9.90,12.00,1.10,10.60,Safe,0.111111,0.091667,0.1060,0.102311,2024
20,29,A & N ISLAND (UT),27.40,24.00,11.20,15.70,Safe,0.408759,0.466667,0.1570,0.381570,2024
21,32,TAMILNADU,5.10,16.00,34.30,45.50,Safe,6.725490,2.143750,0.4550,3.638696,2024
22,33,PUDUCHERRY (UT),6.20,42.00,26.20,51.30,Safe,4.225806,0.623810,0.5130,2.042446,2024
23,35,KERALA,12.80,2.40,31.60,76.50,Semi Critical,2.468750,13.166667,0.7650,6.407167,2024
24,36,LAKSHADWEEP (UT),33.40,1.00,3.40,16.00,Safe,0.101796,3.400000,0.1600,1.432719,2024
25,1,2,3.00,4.00,5.00,6.00,Safe,1.666667,1.250000,0.0600,1.178667,2024
26,1,Andhra Pradesh,9.00,10.79,0.82,7.18,Safe,0.091111,0.075996,0.0718,0.081203,2024
27,2,Arunachal Pradesh,2.16,0.27,1.11,0.34,Safe,0.513889,4.111111,0.0034,1.850680,2024
28,3,Assam,19.45,0.67,6.53,0.56,Safe,0.335733,9.746269,0.0056,4.033921,2024
29,4,Bihar,19.54,8.05,1.14,5.42,Safe,0.058342,0.141615,0.0542,0.090823,2024
30,5,Chhattisgarh,8.57,3.43,0.15,2.03,Safe,0.017503,0.043732,0.0203,0.028554,2024

In [10]:
df.iloc[70:91]

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
70,13,Kurnool,38342.94,17638.70,566.17,10907.07,Over Exploited,0.014766,0.032098,109.0707,21.832886,2024
71,14,Ntr,20780.78,28090.65,1227.81,14159.92,Over Exploited,0.059084,0.043709,141.5992,28.360957,2024
72,15,Nandyal,22651.71,40388.65,66.02,19114.07,Over Exploited,0.002915,0.001635,191.1407,38.229960,2024
73,16,Palnadu,25660.06,55379.59,1215.19,19221.55,Over Exploited,0.047357,0.021943,192.2155,38.470820,2024
74,17,Parvathipuram Manyam,29763.31,35032.83,3586.72,23061.67,Over Exploited,0.120508,0.102382,230.6167,46.212496,2024
75,18,Prakasam,63974.15,19744.85,1072.98,13544.20,Over Exploited,0.016772,0.054342,135.4420,27.116846,2024
76,19,Sri Potti Sriramulu Nellore,68345.39,36991.28,20510.69,71127.23,Over Exploited,0.300103,0.554474,711.2723,142.596291,2024
77,20,Sri Sathya Sai,43077.78,31974.68,595.26,44246.68,Over Exploited,0.013818,0.018617,442.4668,88.506334,2024
78,21,Srikakulam,34587.38,66648.48,2623.08,28333.77,Over Exploited,0.075839,0.039357,283.3377,56.713618,2024
79,22,Tirupati,81366.63,27763.10,87.94,52318.38,Over Exploited,0.001081,0.003168,523.1838,104.638459,2024
80,23,Visakhapatnam,7995.13,3262.26,285.34,1078.97,Over Exploited,0.035689,0.087467,10.7897,2.207202,2024
81,24,Vizianagaram,24997.08,66545.39,2538.33,48662.74,Over Exploited,0.101545,0.038144,486.6274,97.381356,2024
82,25,West Godavari,12011.91,21549.41,235.36,22132.19,Over Exploited,0.019594,0.010922,221.3219,44.276586,2024
83,26,Y.S.R Kadapa,57104.54,20117.22,549.87,29473.80,Over Exploited,0.009629,0.027333,294.7380,58.962385,2024
84,1,2,3.00,4.00,5.00,6.00,Safe,1.666667,1.250000,0.0600,1.178667,2024
85,1,Alluri Sitharama Raju,43956.31,102516.48,2860.84,8890.60,Over Exploited,0.065084,0.027906,88.9060,17.818396,2024
86,2,Anakapalli,22443.69,38195.76,14423.44,6889.74,Over Exploited,0.642650,0.377619,68.8974,14.187588,2024
87,3,Ananthapuramu,40986.63,44150.14,1323.64,35512.65,Over Exploited,0.032294,0.029980,355.1265,71.050210,2024
88,4,Annamayya,44599.19,19166.03,2836.15,19968.94,Over Exploited,0.063592,0.147978,199.6894,40.022508,2024
89,5,Bapatla,23318.20,33572.17,1322.80,12065.45,Over Exploited,0.056728,0.039402,120.6545,24.169352,2024
90,6,Chittoor,55198.12,15130.71,1246.99,18849.65,Over Exploited,0.022591,0.082415,188.4965,37.741302,2024

In [11]:
fig = px.pie(df, names="stage_of_development", title="Stage Distribution")
fig.show()

In [12]:
fig = px.scatter(df, x="risk_score", y="extraction_ratio",
                color="category",
                title="Risk vs Extraction Ratio")
fig.show()

In [13]:
fig = px.sunburst(df, path=["state", "category", "district"], values="annual_extraction", title="Sunburst Chart")
fig.show()