In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

In [2]:
df = pd.read_csv('groundwater_ml_dataset_cleaned.csv')
df

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
0,Himachal Pradesh,Himachal Pradesh,0.61,0.18,0.13,0.20,Safe,0.213115,0.722222,0.0020,0.374535,2024
1,Madhya Pradesh,Madhya Pradesh,27.00,1.68,0.17,7.04,Safe,0.006296,0.101190,0.0704,0.057075,2024
2,Andhra Pradesh,Alluri Sitharama Raju,43956.31,102516.48,2860.84,8890.60,Over Exploited,0.065084,0.027906,88.9060,17.818396,2024
3,Andhra Pradesh,Anakapalli,22443.69,38195.76,14423.44,6889.74,Over Exploited,0.642650,0.377619,68.8974,14.187588,2024
4,Andhra Pradesh,Ananthapuramu,40986.63,44150.14,1323.64,35512.65,Over Exploited,0.032294,0.029980,355.1265,71.050210,2024
...,...,...,...,...,...,...,...,...,...,...,...,...
753,Uttar Pradesh,Amethi,2329.92,2068.95,88.80,260.97,Over Exploited,0.038113,0.042920,2.6097,0.554353,2024
754,Uttar Pradesh,Bareilly,4120.00,3244.34,78.75,540.15,Over Exploited,0.019114,0.024273,5.4015,1.097655,2024
755,Uttar Pradesh,Jhansi,4619.37,2644.95,57.26,1974.42,Over Exploited,0.012396,0.021649,19.7442,3.962458,2024
756,Madhya Pradesh,Madhya Pradesh,317.00,1.00,2.00,314.00,Over Exploited,0.006309,2.000000,3.1400,1.430524,2024
757,Ladakh,Ladakh,18.00,5.00,0.00,13.00,Safe,0.000000,0.000000,0.1300,0.026000,2024

In [3]:
df.isnull().sum()

state                   0
district                0
annual_recharge         0
extractable_resource    0
annual_extraction       0
stage_of_development    0
category                0
extraction_ratio        0
utilization_rate        0
stress_level            0
risk_score              0
year                    0
dtype: int64

In [4]:
df.columns

Index(['state', 'district', 'annual_recharge', 'extractable_resource',
       'annual_extraction', 'stage_of_development', 'category',
       'extraction_ratio', 'utilization_rate', 'stress_level', 'risk_score',
       'year'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 758 entries, 0 to 757
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 758 non-null    object
 1   district              758 non-null    object
 2   annual_recharge       758 non-null    float64
 3   extractable_resource  758 non-null    float64
 4   annual_extraction     758 non-null    float64
 5   stage_of_development  758 non-null    float64
 6   category              758 non-null    object
 7   extraction_ratio      758 non-null    float64
 8   utilization_rate      758 non-null    float64
 9   stress_level          758 non-null    float64
 10  risk_score            758 non-null    float64
 11  year                  758 non-null    int64
dtypes: float64(8), int64(1), object(3)
memory usage: 71.2+ KB

In [6]:
df.tail()

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
753,Uttar Pradesh,Amethi,2329.92,2068.95,88.80,260.97,Over Exploited,0.038113,0.042920,2.6097,0.554353,2024
754,Uttar Pradesh,Bareilly,4120.00,3244.34,78.75,540.15,Over Exploited,0.019114,0.024273,5.4015,1.097655,2024
755,Uttar Pradesh,Jhansi,4619.37,2644.95,57.26,1974.42,Over Exploited,0.012396,0.021649,19.7442,3.962458,2024
756,Madhya Pradesh,Madhya Pradesh,317.00,1.00,2.00,314.00,Over Exploited,0.006309,2.000000,3.1400,1.430524,2024
757,Ladakh,Ladakh,18.00,5.00,0.00,13.00,Safe,0.000000,0.000000,0.1300,0.026000,2024

In [7]:
df.iloc[10:111]

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
10,Andhra Pradesh,Guntur,12414.87,26259.86,2064.53,13762.42,Over Exploited,0.166295,0.078619,137.6242,27.622806,2024
11,Andhra Pradesh,Kakinada,16664.61,59653.79,3486.88,32788.46,Over Exploited,0.209239,0.058452,327.8846,65.683996,2024
12,Andhra Pradesh,Konaseema,15932.71,48720.13,2077.68,45519.00,Over Exploited,0.130403,0.042645,455.1900,91.107219,2024
13,Andhra Pradesh,Krishna,18162.93,90343.85,10846.76,47391.01,Over Exploited,0.597192,0.120061,473.9101,95.068921,2024
14,Andhra Pradesh,Kurnool,38342.94,17638.70,566.17,10907.07,Over Exploited,0.014766,0.032098,109.0707,21.832886,2024
...,...,...,...,...,...,...,...,...,...,...,...,...
106,Assam,DARRANG,41118.91,1500.03,14212.77,1052.21,Over Exploited,0.345650,9.474991,10.5221,6.032676,2024
107,Assam,DHEMAJI,105039.67,302.56,38007.00,67.08,Safe,0.361835,125.618059,0.6708,50.526118,2024
108,Assam,DHUBRI,82305.99,4417.11,18117.49,5033.08,Over Exploited,0.220124,4.101661,50.3308,11.794874,2024
109,Assam,DIBRUGARH,108809.42,2133.21,37792.02,1121.99,Over Exploited,0.347323,17.716034,11.2199,9.469323,2024
110,Assam,DIMA HASAO,43723.76,144.95,19071.65,18.92,Safe,0.436185,131.573991,0.1892,52.841910,2024

In [8]:
fig = px.pie(df,
            names="category",
            title="Groundwater Category Distribution")

fig.show()

In [9]:
fig = px.box(df,
            x="state",
            y="annual_extraction",
            color="state",
            title="Distribution of Extraction by State")

fig.show()

In [10]:
fig = px.histogram(df,
                x="annual_extraction",
                nbins=50, color="annual_extraction",
                title="Distribution of Groundwater Extraction")

fig.show()

In [11]:
fig = px.line(df,
            x="year",
            y="annual_extraction",
            color="state",
            title="Yearly Groundwater Extraction Trend")

fig.show()

In [12]:
fig = px.bar(df,
            x="state",
            y="annual_extraction",
            color="state",
            title="State-wise Annual Groundwater Extraction")

fig.show()

In [13]:
pivot = df.pivot_table(values='risk_score',
                    index='state',
                    columns='stress_level',
                    aggfunc='mean')

fig = px.imshow(pivot,
                title="Heatmap of Stress Level by State")

fig.show()

In [14]:
fig = px.scatter(df,
                x="annual_recharge",
                y="annual_extraction",
                color="stress_level",
                size="risk_score",
                title="Recharge vs Extraction Analysis")

fig.show()

In [15]:
fig = px.choropleth(df,
                    locations="state",
                    locationmode="country names",
                    color="annual_extraction",
                    scope="asia",
                    title="India Groundwater Extraction Map")

fig.show()

In [16]:
fig = px.ecdf(df, x="annual_extraction",
            title="ECDF of Extraction")
fig.show()

In [17]:
fig = px.treemap(df, path=["state", "district"],
                values="annual_extraction",
                title="Treemap of Extraction")
fig.show()

In [18]:
fig = px.sunburst(df, path=["state", "district", "category"],
                values="annual_extraction",
                title="Sunburst Chart")
fig.show()

In [19]:
fig = px.funnel(df, x="annual_extraction", y="category",
                title="Funnel Chart")
fig.show()

In [20]:
fig = px.box(df, x="category", y="annual_extraction",
            points="all", title="Box with Points")
fig.show()

In [21]:
fig = px.violin(df, x="category", y="annual_extraction",
                box=True, title="Violin Plot with Box")
fig.show()