In [17]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [18]:
df = pd.read_csv('groundwater_dataset.csv')
df.head(10)

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category
0,1,Safe,4951,73.39,16.51,66.57,Safe
1,2,Semi Critical,711,10.54,2.82,11.40,Safe
2,3,Critical,206,3.05,0.88,3.55,Safe
3,4,Over-Exploited,751,11.13,4.20,16.93,Safe
4,5,Saline,127,1.88,0.38,1.55,Safe
5,S. No.,Ground Water Resources Assessment,2004,2009,2011,2013.00,Over Exploited
6,2,Safe,4078,71.3,4277,73.20,Semi Critical
7,3,Semi-critical,550,9.6,523,9.00,Safe
8,4,Critical,226,3.9,169,2.90,Safe
9,5,Over-Exploited,839,14.7,802,13.70,Safe

In [19]:
df.isnull().sum()

state                   0
district                0
annual_recharge         0
extractable_resource    0
annual_extraction       0
stage_of_development    0
category                0
dtype: int64

In [20]:
df.columns

Index(['state', 'district', 'annual_recharge', 'extractable_resource',
       'annual_extraction', 'stage_of_development', 'category'],
      dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2060 entries, 0 to 2059
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 2060 non-null   object
 1   district              2060 non-null   object
 2   annual_recharge       2060 non-null   object
 3   extractable_resource  2060 non-null   object
 4   annual_extraction     2060 non-null   object
 5   stage_of_development  2060 non-null   float64
 6   category              2060 non-null   object
dtypes: float64(1), object(6)
memory usage: 112.8+ KB

In [22]:
df.tail()

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category
2055,32,Delhi,34,0,3,31.0,Safe
2056,33,Jammu And Kashmir,149,0,0,149.0,Over Exploited
2057,34,Lakshadweep,5,0,0,5.0,Safe
2058,35,Puducherry,8,0,0,8.0,Safe
2059,36,Ladakh,18,5,0,13.0,Safe

In [23]:
df.describe()

       stage_of_development
count          2.060000e+03
mean           1.300539e+04
std            1.611592e+05
min            0.000000e+00
25%            1.091050e+02
50%            1.965540e+03
75%            1.285486e+04
max            7.283766e+06